### PR TITLE
Add examples for add and remove

### PR DESCRIPTION
**Pull request by eneufeld**
* Extend the set example to show a ref for deepter nesting
* Add an example for an add command
* Add an example for a remove command
* Improve ModelServerCommand interface

### CODE REVIEW

**Comment by tortmayr** [comment]
For me executing the new commands has no effect on the actual model.
I replaced the hardcoded filepaths ("home/eugen..) accordingly. Did I miss something else?

**Comment by eneufeld** [comment]
hmm does the modelserver version fit? I only tested with a modelserver started from the ide

**Comment by eneufeld** [comment]
@tortmayr I retested, with a modelserver started from the `master` everything works, but if I start it from the jar, none of the command actions is working, I also get this error in my log:
`ModelServerBackendContribution: WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/home/eugen/Git/modelserver-theia/example/coffee-theia/build/com.eclipsesource.modelserver.example-0.0.1-SNAPSHOT-standalone.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
`
Maybe something is broken with the jar?

**Comment by eneufeld** [comment]
@tortmayr ok I rechecked and found the problem
the uri in the $ref `file:/home/eugen/Git/modelserver/examples/com.eclipsesource.modelserver.example/.temp/workspace/SuperBrewer3000.coffee#//@workflows.0` must match the workspace as we don't have a workspace set, the modelserver is creating a new workspace for itself. 
So in order for the commands to work with the jar, you have to change this to something like:
`file:/home/eugen/Git/modelserver/theia/example/browser-app/.temp/workspace/SuperBrewer3000.coffee#//@workflows.0`

As far as I know, we can't get the actual workspace from the model server at the moment, but it would be very helpful for this test.

**Comment by eneufeld** [comment]
@tortmayr with the last commit I solved the problem of the hardcoded path in the case the modelserver is started from the jar. 
For a real solution we must either get rid of the path in the ref (would be the best for the clients) or the modelserver must be able to provide us the workspace it is using.

**Comment by tortmayr** [comment]
The temp workspace should never be used in the first place. Theia sends the correct workspace location to the server on application start. Maybe the modelserver-jar is outdated?

The hardcoded solution seems to work fine here but I'm not sure if this will work when used in the coffee editor.

**Comment by tortmayr** [comment]
@eneufeld  I updated the modelserver jar and the workspace uri is now retrieved from the Theia ModelService. As far as I can see everything is now working as expected.

**Comment by eneufeld** [comment]
@tortmayr yes this works. you need to set a workspace in theia which contains the SuperBrewer3000.coffee file though. I didn't do this in my tests :sweat_smile: .

**Review by tortmayr — APPROVED** [review]

**Pull request merged**
